#include "lin/LoweringPasses.h"
#include "PicRuntimeDialect.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/ControlFlow/IR/ControlFlowOps.h"
#include "mlir/Pass/Pass.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinOps.h"

using namespace mlir;

namespace {

struct PicRuntimeGPUHelperPass : public PassWrapper<PicRuntimeGPUHelperPass, OperationPass<ModuleOp>> {
  MLIR_DEFINE_EXPLICIT_INTERNAL_INLINE_TYPE_ID(PicRuntimeGPUHelperPass)
  bool enableGPU;
  PicRuntimeGPUHelperPass(bool enableGPU) : enableGPU(enableGPU) {}

  void runOnOperation() override {
    if (!enableGPU) return;

    ModuleOp module = getOperation();
    OpBuilder builder(module.getContext());
    Location loc = module.getLoc();
    auto i32Type = builder.getI32Type();
    auto i64Type = builder.getI64Type();
    auto i1Type = builder.getI1Type();

    // Erase existing worker_thread (generated by PicReduceToRuntimePass with full dispatch)
    if (auto existing = module.lookupSymbol<func::FuncOp>("worker_thread")) {
      existing.erase();
    }

    // Create pic_gpu_dispatch_helper declaration
    if (!module.lookupSymbol<func::FuncOp>("pic_gpu_dispatch_helper")) {
      OpBuilder modB(module.getBodyRegion());
      modB.setInsertionPointToEnd(module.getBody());
      auto helperTy = modB.getFunctionType({i32Type, i32Type, i64Type}, {});
      auto helper = modB.create<func::FuncOp>(loc, "pic_gpu_dispatch_helper", helperTy);
      helper.setPrivate();
    }

    // Create new worker_thread with GPU delegation
    builder.setInsertionPointToEnd(module.getBody());
    auto wType = builder.getFunctionType({i64Type}, {i64Type});
    auto wFunc = builder.create<func::FuncOp>(loc, "worker_thread", wType);
    Block *wEntry = wFunc.addEntryBlock();
    Value stateArg = wEntry->getArgument(0);

    Block *lHead = wFunc.addBlock();
    Block *lBody = wFunc.addBlock();
    Block *lEnd = wFunc.addBlock();

    builder.setInsertionPointToStart(wEntry);
    Value c0_i64 = builder.create<arith::ConstantOp>(loc, i64Type, builder.getI64IntegerAttr(0));
    builder.create<cf::BranchOp>(loc, lHead);

    builder.setInsertionPointToStart(lHead);
    auto popOp = builder.create<pic::runtime::PopRedexOp>(loc, i1Type, i32Type, i32Type);
    Value valid = popOp.getValid();
    Value nodeA = popOp.getNodeA();
    Value nodeB = popOp.getNodeB();
    builder.create<cf::CondBranchOp>(loc, valid, lBody, ValueRange{nodeA, nodeB}, lEnd, ValueRange{});

    Value bodyNodeA = lBody->addArgument(i32Type, loc);
    Value bodyNodeB = lBody->addArgument(i32Type, loc);
    builder.setInsertionPointToStart(lBody);

    builder.create<func::CallOp>(loc, TypeRange{}, "pic_gpu_dispatch_helper",
        ValueRange{bodyNodeA, bodyNodeB, stateArg});
    builder.create<cf::BranchOp>(loc, lHead);

    builder.setInsertionPointToStart(lEnd);
    builder.create<func::ReturnOp>(loc, ValueRange{c0_i64});
  }
};

} // namespace

std::unique_ptr<Pass> createPicRuntimeGPUHelperPass(bool enableGPU) { return std::make_unique<PicRuntimeGPUHelperPass>(enableGPU); }
